create table if not exists chat_users (
    id int primary key generated by default as identity,
    user_id uuid not null references auth.users(id) on delete cascade on update cascade,
    chat_id uuid not null,
    created_at timestamptz default now()
);