create table "public"."chat_users" (
    "id" integer generated by default as identity not null,
    "user_id" uuid not null,
    "chat_id" uuid not null,
    "created_at" timestamp with time zone default now()
);


CREATE UNIQUE INDEX chat_users_pkey ON public.chat_users USING btree (id);

alter table "public"."chat_users" add constraint "chat_users_pkey" PRIMARY KEY using index "chat_users_pkey";

alter table "public"."chat_users" add constraint "chat_users_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."chat_users" validate constraint "chat_users_user_id_fkey";

grant delete on table "public"."chat_users" to "anon";

grant insert on table "public"."chat_users" to "anon";

grant references on table "public"."chat_users" to "anon";

grant select on table "public"."chat_users" to "anon";

grant trigger on table "public"."chat_users" to "anon";

grant truncate on table "public"."chat_users" to "anon";

grant update on table "public"."chat_users" to "anon";

grant delete on table "public"."chat_users" to "authenticated";

grant insert on table "public"."chat_users" to "authenticated";

grant references on table "public"."chat_users" to "authenticated";

grant select on table "public"."chat_users" to "authenticated";

grant trigger on table "public"."chat_users" to "authenticated";

grant truncate on table "public"."chat_users" to "authenticated";

grant update on table "public"."chat_users" to "authenticated";

grant delete on table "public"."chat_users" to "service_role";

grant insert on table "public"."chat_users" to "service_role";

grant references on table "public"."chat_users" to "service_role";

grant select on table "public"."chat_users" to "service_role";

grant trigger on table "public"."chat_users" to "service_role";

grant truncate on table "public"."chat_users" to "service_role";

grant update on table "public"."chat_users" to "service_role";


